# AppVeyor configuration based on https://github.com/guedou/scapy-appveyor/blob/master/appveyor.yml

version: "v0.1.15.dev0-{build}"

environment:

  # Python versions that will be tested
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      ARCH: "32"
      PLAT_NAME: "win32"

    - PYTHON: "C:\\Python27-x64"
      PYTHON_VERSION: "2.7.x"
      ARCH: "64"
      PLAT_NAME: "win-amd64"

# Install requirements
install:
  # Set path
  - "set PYTHONPATH=%APPVEYOR_BUILD_FOLDER%"
  - "set PATH=%APPVEYOR_BUILD_FOLDER%;%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Install whell for building
  - "python.exe -m pip install wheel"

  # Installing Npcap
  - ps: iex ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/secdev/scapy/master/.appveyor/InstallNpcap.ps1'))
  - refreshenv

  # Set the proper build program
  - if "%ARCH%"=="32" (call "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\vcvarsall.bat" x86)
  - if "%ARCH%"=="64" (call "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\VC\\vcvarsall.bat" amd64)

  # Build and install the library
  - "python.exe setup.py install"

  # Install optional requirements
  - "pip install -r requirements-docs.txt"
  - "pip install -r requirements-optional.txt"

build: off

test_script:
  # Run tests
  #- "python.exe setup.py test"
  # Build the docs
  - "python.exe setup.py doc"

after_test:
  # Build a source artifact
  - "python.exe setup.py sdist"
  # Build a wheel artifact
  - "python.exe setup.py bdist_wheel"

artifacts:
  - path: dist\*.whl

deploy:
  release: "pysap $(APPVEYOR_REPO_TAG_NAME)"
  provider: GitHub
  auth_token:
    secure: E3woIwT5J6hCuCVvP2u7Pc+r1mS1hG0dGwoYntsNZHXVqZ0V3DiqefqneBmTXmPZ
  artifact: dist\*.whl
  draft: true
  force_update: true
  on:
    branch: master
    appveyor_repo_tag: true
